version: "3.8"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  lbg-car-react-starter:
    image: troycooper/lbg-car-react-starter
    build: ./lbg-car-react-starter
    ports:
      - target: 80
        published: 80

  lbg-car-spring-app-starter:
    image: troycooper/lbg-car-spring-app-starter
    build:
      context: ./lbg-car-spring-app-starter
    networks:
      - app-network
    ports:
      - target: 8000
        published: 8000

networks:
  app-network:

volumes:
  db-data: